// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planning.Infrastructure.Data;

#nullable disable

namespace Planning.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    partial class PlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planning")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planning.Domain.Entities.Setlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessCode")
                        .IsUnique();

                    b.ToTable("Setlists", "planning");
                });

            modelBuilder.Entity("Planning.Domain.Entities.SetlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerformanceNote")
                        .HasColumnType("text");

                    b.Property<Guid>("SetlistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SetlistId");

                    b.ToTable("SetlistItems", "planning");
                });

            modelBuilder.Entity("Planning.Domain.Entities.SetlistItem", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Setlist", null)
                        .WithMany("Items")
                        .HasForeignKey("SetlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Planning.Domain.Entities.Setlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
